version: '2'
services:
  db:
    image: elasticsearch
    ports:
      - "9200:9200"
  web:
    image: kibana
    ports:
      - "5601:5601"
    depends_on:
      - db
    environment:
      - ELASTICSEARCH_URL=http://db:9200
